name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://cvws.icloud-content.com/B/AYOApWyzLjuglF1NicBO6HQ4kOd3AbXgbA2DpJ2VRsPVtoPoLXrXJo2z/TWRP+STOCK+ROM+AUGUST.zip?o=Am-E3rpY68TXLXVCR94xVoVWlA3RxhvLcNAE1RDlAcWj&v=1&x=3&a=CAogj5dKgCu0SssRAlX0h8rmhZ823Se2I20WLRjH7hjj8n0SbxCO-aiR2i4YrvDfkdouIgEAUgQ4kOd3WgTXJo2zaidG4F42y5xKmrcvE8mrJcqeNCUTf9Y0aByLe4JXnOSb48--oa-zGnpyJxZkOoxYoMbRKIeCRdOFignSDuGYMI9Xm7zbRszF2iXuOoZC_NEH4A&e=1604744378&fl=&r=06df7a70-a9ee-4a8c-9ccd-46d483a28577-1&k=mTedNzSEWxB2WvKJLLYwug&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=46&s=Yie4n8-K7CbOWVdMkw0CzVHL8tQ
  ROM_NAME: Generic
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              mkdir final
              zip -r final/GSI.zip /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/
       
       - name: Upload GSI to BitSend
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer bit final/GSI.zip

         
            
